In [51]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import accuracy_score, classification_report, confusion_matrix


In [52]:
c_data=pd.read_csv('Company_Data.csv')

In [53]:
c_data.head()

Sales  CompPrice  Income  Advertising  Population  Price ShelveLoc  Age  \
0   9.50        138      73           11         276    120       Bad   42   
1  11.22        111      48           16         260     83      Good   65   
2  10.06        113      35           10         269     80    Medium   59   
3   7.40        117     100            4         466     97    Medium   55   
4   4.15        141      64            3         340    128       Bad   38   

   Education Urban   US  
0         17   Yes  Yes  
1         10   Yes  Yes  
2         12   Yes  Yes  
3         14   Yes  Yes  
4         13   Yes   No

In [54]:
c_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 400 entries, 0 to 399
Data columns (total 11 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   Sales        400 non-null    float64
 1   CompPrice    400 non-null    int64  
 2   Income       400 non-null    int64  
 3   Advertising  400 non-null    int64  
 4   Population   400 non-null    int64  
 5   Price        400 non-null    int64  
 6   ShelveLoc    400 non-null    object 
 7   Age          400 non-null    int64  
 8   Education    400 non-null    int64  
 9   Urban        400 non-null    object 
 10  US           400 non-null    object 
dtypes: float64(1), int64(7), object(3)
memory usage: 34.5+ KB


In [55]:
c_data.shape

(400, 11)

In [56]:
c_data.isnull().sum()

Sales          0
CompPrice      0
Income         0
Advertising    0
Population     0
Price          0
ShelveLoc      0
Age            0
Education      0
Urban          0
US             0
dtype: int64

In [57]:
# Assuming a threshold of 200 for categorizing sales as high or low
c_data['Sales_Category'] = c_data['Sales'].apply(lambda x: 'High' if x > 200 else 'Low')

# Drop the original 'Sales' column
c_data.drop('Sales', axis=1, inplace=True)

# Display the updated dataset
print(c_data.head())


   CompPrice  Income  Advertising  Population  Price ShelveLoc  Age  \
0        138      73           11         276    120       Bad   42   
1        111      48           16         260     83      Good   65   
2        113      35           10         269     80    Medium   59   
3        117     100            4         466     97    Medium   55   
4        141      64            3         340    128       Bad   38   

   Education Urban   US Sales_Category  
0         17   Yes  Yes            Low  
1         10   Yes  Yes            Low  
2         12   Yes  Yes            Low  
3         14   Yes  Yes            Low  
4         13   Yes   No            Low  


In [58]:
#Creating dummy vairables dropping first dummy variable
c_data=pd.get_dummies(c_data,columns=['Urban','US'], drop_first=True)

In [59]:
from sklearn.metrics import f1_score
from sklearn.model_selection import train_test_split

In [60]:
c_data['ShelveLoc']=c_data['ShelveLoc'].map({'Good':1,'Medium':2,'Bad':3})

In [61]:
print(c_data.head())

   CompPrice  Income  Advertising  Population  Price  ShelveLoc  Age  \
0        138      73           11         276    120          3   42   
1        111      48           16         260     83          1   65   
2        113      35           10         269     80          2   59   
3        117     100            4         466     97          2   55   
4        141      64            3         340    128          3   38   

   Education Sales_Category  Urban_Yes  US_Yes  
0         17            Low       True    True  
1         10            Low       True    True  
2         12            Low       True    True  
3         14            Low       True    True  
4         13            Low       True   False  


In [62]:
x=c_data.iloc[:,0:6]
y=c_data['ShelveLoc']
x

CompPrice  Income  Advertising  Population  Price  ShelveLoc
0          138      73           11         276    120          3
1          111      48           16         260     83          1
2          113      35           10         269     80          2
3          117     100            4         466     97          2
4          141      64            3         340    128          3
..         ...     ...          ...         ...    ...        ...
395        138     108           17         203    128          1
396        139      23            3          37    120          2
397        162      26           12         368    159          2
398        100      79            7         284     95          3
399        134      37            0          27    120          1

[400 rows x 6 columns]

In [63]:
y

0      3
1      1
2      2
3      2
4      3
      ..
395    1
396    2
397    2
398    3
399    1
Name: ShelveLoc, Length: 400, dtype: int64

In [64]:
c_data['ShelveLoc'].unique()

array([3, 1, 2], dtype=int64)

In [65]:
c_data.ShelveLoc.value_counts()

ShelveLoc
2    219
3     96
1     85
Name: count, dtype: int64

In [66]:
colnames = list(c_data.columns)
colnames

['CompPrice',
 'Income',
 'Advertising',
 'Population',
 'Price',
 'ShelveLoc',
 'Age',
 'Education',
 'Sales_Category',
 'Urban_Yes',
 'US_Yes']

In [67]:
# Descriptive statistics for each column
c_data.describe()

CompPrice      Income  Advertising  Population       Price  \
count  400.000000  400.000000   400.000000  400.000000  400.000000   
mean   124.975000   68.657500     6.635000  264.840000  115.795000   
std     15.334512   27.986037     6.650364  147.376436   23.676664   
min     77.000000   21.000000     0.000000   10.000000   24.000000   
25%    115.000000   42.750000     0.000000  139.000000  100.000000   
50%    125.000000   69.000000     5.000000  272.000000  117.000000   
75%    135.000000   91.000000    12.000000  398.500000  131.000000   
max    175.000000  120.000000    29.000000  509.000000  191.000000   

        ShelveLoc         Age   Education  
count  400.000000  400.000000  400.000000  
mean     2.027500   53.322500   13.900000  
std      0.672961   16.200297    2.620528  
min      1.000000   25.000000   10.000000  
25%      2.000000   39.750000   12.000000  
50%      2.000000   54.500000   14.000000  
75%      2.000000   66.000000   16.000000  
max      3.000000   80.000000   18.000000

In [68]:
c_data.head()

CompPrice  Income  Advertising  Population  Price  ShelveLoc  Age  \
0        138      73           11         276    120          3   42   
1        111      48           16         260     83          1   65   
2        113      35           10         269     80          2   59   
3        117     100            4         466     97          2   55   
4        141      64            3         340    128          3   38   

   Education Sales_Category  Urban_Yes  US_Yes  
0         17            Low       True    True  
1         10            Low       True    True  
2         12            Low       True    True  
3         14            Low       True    True  
4         13            Low       True   False

In [69]:
c_data['Sales_Category'] = c_data['Sales_Category'].map({'Low': 0, 'High': 1})

In [70]:
# Labels are the values we want to predict
y = np.array(c_data['Income'])
# Remove the labels from the features
# axis 1 refers to the columns
X = c_data.drop('Income', axis = 1)

In [71]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [72]:
print('Training Features Shape:', X_train.shape)
print('Training Labels Shape:', y_train.shape)
print('Testing Features Shape:', X_test.shape)
print('Testing Labels Shape:', y_test.shape)

Training Features Shape: (320, 10)
Training Labels Shape: (320,)
Testing Features Shape: (80, 10)
Testing Labels Shape: (80,)


## Build a Random forest model

In [73]:
rf_model = RandomForestClassifier(n_estimators=100, random_state=42)
rf_model.fit(X_train, y_train)

RandomForestClassifier(random_state=42)

In [74]:
y_pred = rf_model.predict(X_test)


In [75]:
print("Accuracy:", accuracy_score(y_test, y_pred))
print("\nConfusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred, zero_division=1))


Accuracy: 0.0125

Confusion Matrix:
 [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 1 0 ... 0 0 0]]

Classification Report:
               precision    recall  f1-score   support

          21       1.00      0.00      0.00         1
          22       0.00      1.00      0.00         0
          23       1.00      0.00      0.00         1
          24       1.00      0.00      0.00         1
          25       0.00      0.00      0.00         3
          26       0.00      1.00      0.00         0
          28       0.00      0.00      0.00         1
          29       0.00      0.00      0.00         1
          30       0.33      1.00      0.50         1
          32       0.00      0.00      0.00         1
          33       0.00      1.00      0.00         0
          35       0.00      1.00      0.00         0
          36       0.00      1.00      0.00         0
          37       0.00      1.00      0.00         0
       